name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

env:
  PROJECT_NAME: exordos-base
  REPO_ENDPOINT_PUT: http://10.20.0.1:8082

jobs:
  Build:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 30
      - name: Build Exordos Core
        run: |
          set -eux
          
          source ~/.profile
          genesis build $(pwd)

          # Temporary upload step is done in the build script
          VERSION="$(genesis --silent get-version .)"

          # Prepare `raw` and `raw.gz` images
          cd output
          qemu-img convert -f qcow2 exordos-base.qcow2 -O raw exordos-base.raw
          gzip -5 -k < exordos-base.raw > exordos-base.raw.gz

          # Upload the VM images
          curl -X PUT --upload-file exordos-base.qcow2 \
            ${REPO_ENDPOINT_PUT}/${PROJECT_NAME}/${VERSION}/exordos-base.qcow2
          curl -X PUT --upload-file exordos-base.raw.gz \
            ${REPO_ENDPOINT_PUT}/${PROJECT_NAME}/${VERSION}/exordos-base.raw.gz
          curl -X PUT --upload-file exordos-base.raw \
            ${REPO_ENDPOINT_PUT}/${PROJECT_NAME}/${VERSION}/exordos-base.raw

          sha256sum exordos-base.qcow2 >> SHA256SUMS
          sha256sum exordos-base.raw.gz >> SHA256SUMS
          sha256sum exordos-base.raw >> SHA256SUMS

          curl -X PUT --upload-file SHA256SUMS \
            ${REPO_ENDPOINT_PUT}/${PROJECT_NAME}/${VERSION}/SHA256SUMS
          cd -
